### PR TITLE
ru_ru translate

### PR DESCRIPTION
**Pull request by Loverxzc**
The translation is not finished yet. Tomorrow there will be a full translation

### CODE REVIEW

**Comment by Yesssssman** [comment]
Have you read FAQ?

**Comment by Loverxzc** [comment]
Where is it? I can't find FAQ

**Comment by Yesssssman** [comment]
In the mod description on the Curseforge page, I mentioned that I won't accept any particular translation file. Instead, you can distribute your language file on your personal site or whatever.

**Comment by Loverxzc** [comment]
Ok, good luck with the mod

**Comment by MiniRaptor** [comment]
Why you don't accept any translation for mod?

**Comment by Yesssssman** [comment]
Cause I dont't want to be tackled from translation error made by other people. The only language I'm struggling with is enough in English

**Pull request closed without merging**
