### PR TITLE
Support 1.19.2

### PR DESCRIPTION
**Pull request by ISNing**
Tested. But there are still two "FIXME" where I don't understand need to be reviewed

### CODE REVIEW

**Comment by ISNing** [comment]
What's more, although I think this may should pr to branch 1.19.2, as for it didn't exist, I don't know how to do that, sorry~

**Comment by ISNing** [comment]
[epicfight-18.3.8.zip](https://github.com/Yesssssman/epicfightmod/files/12260089/epicfight-18.3.8.zip)
Here's artifacts I built, remember to change it's extension to `.jar`

**Comment by Manwe03** [comment]
please, make the 1.19.2 branch public in curseforge

**Comment by ISNing** [comment]
> please, make the 1.19.2 branch public in curseforge

Sorry, but I don't think I have enough free time to maintain it
You can just use the jar I have already built, it's been tested and no obvious bug has been found

**Comment by Kasualix** [comment]
Can be closed now. ~It seems like their GitHub is just for show to external contributors.~

**Comment by ISNing** [comment]
> Can be closed now. ~It seems like their GitHub is just for show to external contributors.~

You're right, maybe the have never expected someone to contribute to this.....

**Comment by MetalKnight56** [comment]
> Can be closed now. ~It seems like their GitHub is just for show to external contributors.~

I don't get what you mean in "just for show" ? We decide what we accept or not, if we didn't accept the request back then it means that we don't want that contribution for now. We thank the author for helping us on this, but we have our own contributors that made the port in our own models. If you don't comprehend that, i don't think you are in the right place.

**Pull request closed without merging**
